// export const citiesDropDown = [
//   'Karachi',
//   'Lahore',
//   'Faisalabad',
//   'Serai',
//   'Rawalpindi',
//   'Multan',
//   'Gujranwala',
//   'Hyderabad City',
//   'Peshawar',
//   'Abbottabad',
//   'Islamabad',
//   'Quetta',
//   'Bannu',
//   'Bahawalpur',
//   'Sargodha',
//   'Sialkot City',
//   'Sukkur',
//   'Larkana',
//   'Sheikhupura',
//   'Mirpur Khas',
//   'Rahamyar Khan',
//   'Kohat',
//   'Jhang Sadr',
//   'Gujrat',
//   'Bardar',
//   'Kasar',
//   'Dera Ghazi Khan',
//   'Masawala',
//   'Nawabshah',
//   'Okara',
//   'Gilgit',
//   'Chiniot',
//   'Sadiqabad',
//   'Turbat',
//   'Dera Ismail Khan',
//   'Chaman',
//   'Zhob',
//   'Mehra',
//   'Parachinar',
//   'Gwadar',
//   'Kundian',
//   'Shahdad Kot',
//   'Harapur',
//   'Matiari',
//   'Dera Allahyar',
//   'Lodhran',
//   'Batgram',
//   'Thatta',
//   'Bagh',
//   'Badan',
//   'Mansehra',
//   'Ziarat',
//   'Muzaffargarh',
//   'Tando Allahyar',
//   'Dera Murad Jamali',
//   'Karak',
//   'Mardan',
//   'Uthal',
//   'Nankana Sahib',
//   'Barkhan',
//   'Hafizabad',
//   'Kotli',
//   'Loralai',
//   'Dera Bugti',
//   'Jhang City',
//   'Sahawal',
//   'Sanghar',
//   'Pakpattan',
//   'Chakwal',
//   'Khushab',
//   'Ghotki',
//   'Kohlu',
//   'Khuzdar',
//   'Awaran',
//   'Nowshera',
//   'Charsadda',
//   'Qila Abdullah',
//   'Bahawalnagar',
//   'Dadu',
//   'Alaabad',
//   'Lakki Marwat',
//   'Chilas',
//   'Pishin',
//   'Tank',
//   'Chitral',
//   'Qila Saifullah',
//   'Shikarpur',
//   'Panjgar',
//   'Mastung',
//   'Kalat',
//   'Gandava',
//   'Khanewal',
//   'Narowal',
//   'Khairpur',
//   'Malakand',
//   'Vihari',
//   'Saidu Sharif',
//   'Jhelum',
//   'Mandi Bahauddan',
//   'Bhakkar',
//   'Toba Tek Singh',
//   'Jamshoro',
//   'Kharan',
//   'Umarkot',
//   'Hangu',
//   'Timargara',
//   'Gakuch',
//   'Jacobabad',
//   'Alparai',
//   'Mianwali',
//   'Masa Khel Bazar',
//   'Naushahro Faroz',
//   'New Mirpur',
//   'Daggar',
//   'Eidgah',
//   'Sibi',
//   'Dalbandan',
//   'Rajanpur',
//   'Leiah',
//   'Upper Dir',
//   'Tando Muhammad Khan',
//   'Attock City',
//   'Rawala Kot',
//   'Swabi',
//   'Kandhkot',
//   'Dasu',
//   'Athmuqam',
// ];
export const citiesDropDown = [
  {key: 'Pakistan', value: 'Karachi'},
  {key: 'Pakistan', value: 'Lahore'},
  {key: 'Pakistan', value: 'Faisalabad'},
  {key: 'Pakistan', value: 'Serai'},
  {key: 'Pakistan', value: 'Rawalpindi'},
  {key: 'Pakistan', value: 'Multan'},
  {key: 'Pakistan', value: 'Gujranwala'},
  {key: 'Pakistan', value: 'Hyderabad City'},
  {key: 'Pakistan', value: 'Peshawar'},
  {key: 'Pakistan', value: 'Abbottabad'},
  {key: 'Pakistan', value: 'Islamabad'},
  {key: 'Pakistan', value: 'Quetta'},
  {key: 'Pakistan', value: 'Bannu'},
  {key: 'Pakistan', value: 'Bahawalpur'},
  {key: 'Pakistan', value: 'Sargodha'},
  {key: 'Pakistan', value: 'Sialkot City'},
  {key: 'Pakistan', value: 'Sukkur'},
  {key: 'Pakistan', value: 'Larkana'},
  {key: 'Pakistan', value: 'Sheikhupura'},
  {key: 'Pakistan', value: 'Mirpur Khas'},
  {key: 'Pakistan', value: 'Rahamyar Khan'},
  {key: 'Pakistan', value: 'Kohat'},
  {key: 'Pakistan', value: 'Jhang Sadr'},
  {key: 'Pakistan', value: 'Gujrat'},
  {key: 'Pakistan', value: 'Bardar'},
  {key: 'Pakistan', value: 'Kasar'},
  {key: 'Pakistan', value: 'Dera Ghazi Khan'},
  {key: 'Pakistan', value: 'Masawala'},
  {key: 'Pakistan', value: 'Nawabshah'},
  {key: 'Pakistan', value: 'Okara'},
  {key: 'Pakistan', value: 'Gilgit'},
  {key: 'Pakistan', value: 'Chiniot'},
  {key: 'Pakistan', value: 'Sadiqabad'},
  {key: 'Pakistan', value: 'Turbat'},
  {key: 'Pakistan', value: 'Dera Ismail Khan'},
  {key: 'Pakistan', value: 'Chaman'},
  {key: 'Pakistan', value: 'Zhob'},
  {key: 'Pakistan', value: 'Mehra'},
  {key: 'Pakistan', value: 'Parachinar'},
  {key: 'Pakistan', value: 'Gwadar'},
  {key: 'Pakistan', value: 'Kundian'},
  {key: 'Pakistan', value: 'Shahdad Kot'},
  {key: 'Pakistan', value: 'Harapur'},
  {key: 'Pakistan', value: 'Matiari'},
  {key: 'Pakistan', value: 'Dera Allahyar'},
  {key: 'Pakistan', value: 'Lodhran'},
  {key: 'Pakistan', value: 'Batgram'},
  {key: 'Pakistan', value: 'Thatta'},
  {key: 'Pakistan', value: 'Bagh'},
  {key: 'Pakistan', value: 'Badan'},
  {key: 'Pakistan', value: 'Mansehra'},
  {key: 'Pakistan', value: 'Ziarat'},
  {key: 'Pakistan', value: 'Muzaffargarh'},
  {key: 'Pakistan', value: 'Tando Allahyar'},
  {key: 'Pakistan', value: 'Dera Murad Jamali'},
  {key: 'Pakistan', value: 'Karak'},
  {key: 'Pakistan', value: 'Mardan'},
  {key: 'Pakistan', value: 'Uthal'},
  {key: 'Pakistan', value: 'Nankana Sahib'},
  {key: 'Pakistan', value: 'Barkhan'},
  {key: 'Pakistan', value: 'Hafizabad'},
  {key: 'Pakistan', value: 'Kotli'},
  {key: 'Pakistan', value: 'Loralai'},
  {key: 'Pakistan', value: 'Dera Bugti'},
  {key: 'Pakistan', value: 'Jhang City'},
  {key: 'Pakistan', value: 'Sahawal'},
  {key: 'Pakistan', value: 'Sanghar'},
  {key: 'Pakistan', value: 'Pakpattan'},
  {key: 'Pakistan', value: 'Chakwal'},
  {key: 'Pakistan', value: 'Khushab'},
  {key: 'Pakistan', value: 'Ghotki'},
  {key: 'Pakistan', value: 'Kohlu'},
  {key: 'Pakistan', value: 'Khuzdar'},
  {key: 'Pakistan', value: 'Awaran'},
  {key: 'Pakistan', value: 'Nowshera'},
  {key: 'Pakistan', value: 'Charsadda'},
  {key: 'Pakistan', value: 'Qila Abdullah'},
  {key: 'Pakistan', value: 'Bahawalnagar'},
  {key: 'Pakistan', value: 'Alaabad'},
  {key: 'Pakistan', value: 'Lakki Marwat'},
  {key: 'Pakistan', value: 'Chilas'},
  {key: 'Pakistan', value: 'Pishin'},
  {key: 'Pakistan', value: 'Tank'},
  {key: 'Pakistan', value: 'Chitral'},
  {key: 'Pakistan', value: 'Qila Saifullah'},
  {key: 'Pakistan', value: 'Shikarpur'},
  {key: 'Pakistan', value: 'Panjgar'},
  {key: 'Pakistan', value: 'Mastung'},
  {key: 'Pakistan', value: 'Kalat'},
  {key: 'Pakistan', value: 'Gandava'},
  {key: 'Pakistan', value: 'Khanewal'},
  {key: 'Pakistan', value: 'Narowal'},
  {key: 'Pakistan', value: 'Khairpur'},
  {key: 'Pakistan', value: 'Malakand'},
  {key: 'Pakistan', value: 'Vihari'},
  {key: 'Pakistan', value: 'Saidu Sharif'},
  {key: 'Pakistan', value: 'Jhelum'},
  {key: 'Pakistan', value: 'Mandi Bahauddan'},
  {key: 'Pakistan', value: 'Bhakkar'},
  {key: 'Pakistan', value: 'Toba Tek Singh'},
  {key: 'Pakistan', value: 'Jamshoro'},
  {key: 'Pakistan', value: 'Kharan'},
  {key: 'Pakistan', value: 'Umarkot'},
  {key: 'Pakistan', value: 'Hangu'},
  {key: 'Pakistan', value: 'Timargara'},
  {key: 'Pakistan', value: 'Gakuch'},
  {key: 'Pakistan', value: 'Jacobabad'},
  {key: 'Pakistan', value: 'Alparai'},
  {key: 'Pakistan', value: 'Mianwali'},
  {key: 'Pakistan', value: 'Masa Khel Bazar'},
  {key: 'Pakistan', value: 'Naushahro Faroz'},
  {key: 'Pakistan', value: 'New Mirpur'},
  {key: 'Pakistan', value: 'Daggar'},
  {key: 'Pakistan', value: 'Eidgah'},
  {key: 'Pakistan', value: 'Sibi'},
  {key: 'Pakistan', value: 'Dalbandan'},
  {key: 'Pakistan', value: 'Rajanpur'},
  {key: 'Pakistan', value: 'Leiah'},
  {key: 'Pakistan', value: 'Upper Dir'},
  {key: 'Pakistan', value: 'Tando Muhammad Khan'},
  {key: 'Pakistan', value: 'Attock City'},
  {key: 'Pakistan', value: 'Rawala Kot'},
  {key: 'Pakistan', value: 'Swabi'},
  {key: 'Pakistan', value: 'Kandhkot'},
  {key: 'Pakistan', value: 'Dasu'},
  {key: 'Pakistan', value: 'Athmuqam'},
];

export const countryList = [
  'Pakistan',
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'British Virgin Islands',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Cape Verde',
  'Cayman Islands',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Congo',
  'Cook Islands',
  'Costa Rica',
  'Cote D Ivoire',
  'Croatia',
  'Cruise Ship',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia',
  'French West Indies',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kuwait',
  'Kyrgyz Republic',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Pierre and Miquelon',
  'Samoa',
  'San Marino',
  'Satellite',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'St Kitts and Nevis',
  'St Lucia',
  'St Vincent',
  'St. Lucia',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  "Timor L'Este",
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (US)',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];
